### ISSUE TITLE
FPS physics

### ISSUE THREAD

**Issue by danielribeiro** [schteppe/cannon.js#102]
Hi,

Is there any plan on handling [fps physics](http://oxleygamedev.blogspot.com/2011/04/player-physics-part-2.html)?

Cheers,
- Daniel

**Comment by donmccurdy** [comment]
I've been looking into this with Three.js/Cannon/A-Frame a bit:

[Platformer demo](https://sandbox.donmccurdy.com/vr/platforms/)
[Static and dynamic bodies demo](https://sandbox.donmccurdy.com/vr/playground/)

The code is [here](https://github.com/donmccurdy/aframe-extras/blob/master/src/physics/kinematic-body.js), and turned out quite similar to the article @danielribeiro posted. Cannon is really helpful for providing the collisions and normals (so I have surfaces to project motion against) but I'm copying player position/velocity data from the scene into Cannon, not the other way around.

It's working fairly well, at least on simple terrain. Trying to walk across a trimesh or between adjacent platforms (which might have some fractional space between them?) has caused weird issues where the contact normals aren't vertical and the player sinks into the floor. Example [here](https://sandbox.donmccurdy.com/vr/monument/), if you walk around on the upper platforms you'll probably sink in some.

**Comment by danielribeiro** [comment]
@donmccurdy  this looks amazing.

**Comment by Ranzear** [comment]
@donmccurdy When your dynamic bodies push the boxes around, the boxes don't push the player. This results in some funny behavior if you put a box on the elevator and try to stand on it: it squeezes and then rockets out sideways.

**Comment by donmccurdy** [comment]
@Ranzear yeah there are glitches for sure. The boxes do push the player, in the sense that the player won't fall through. But that need some work.
