### ISSUE TITLE
I don't understand heightfield?

### ISSUE THREAD

**Issue by rbozan** [schteppe/cannon.js#221]
```javascript
        this.objects.sphereBody = new CANNON.Body({
		   mass: 5, // kg
		   position: new CANNON.Vec3(1, 1, 800), // m
		   shape: new CANNON.Sphere(5)
		});
		this.world.addBody(this.objects.sphereBody);

		var tempHeightMap = [];
		for (x = 0; x < this.heightMap.length; x++) {
			tempHeightMap[x] = [];
			for (y = 0; y < this.heightMap[x].length; y++) {
				tempHeightMap[x][y] = this.heightMap[x][y].z;
			}
		}

		var heightfieldShape = new CANNON.Heightfield(tempHeightMap, {
	        elementSize: 1
	    });

		this.objects.heightfieldBody = new CANNON.Body({ mass: 0 });
        this.objects.heightfieldBody.addShape(heightfieldShape);
        this.world.addBody(this.objects.heightfieldBody);
```

I can see that this.objects.heightfieldBody actually got the z-heights (console.log(this.objects.heightfieldBody.shapes[0].data), but for some reason the sphere does not collide with the heightfield.

Here's most of the data from this.objects.heightfieldBody:
https://gist.github.com/youssefdetovernickr/dcef8d596efcedde54d4

**Comment by schteppe** [comment]
Looks legit to me. If you copy/paste the value of ```tempHeightMap``` into the heightfield demo in the cannon repo, maybe you can see what's wrong?

**Comment by youssefdetovernickr** [comment]
@schteppe Well.. tempHeightMap basically retrieves everything from an other variable (this.heightMap) which is a procedural terrain.. So I think it's smarter to show you all of the data of objects.heightfieldBody. I've however restricted the heightfield to 20 - 20:

https://gist.github.com/youssefdetovernickr/39df2d9298a9c64bc251

**Comment by youssefdetovernickr** [comment]
Fixed it by changing the data which contains -Infinity to 0. Pretty much my fault, but to be honest it should not see -Infinity as the minValue, as this bugs the whole Heightfield..

**Comment by that-ben** [comment]
For anybody coming here later on with a similar issue, this might be of use: I had that happening to me too and found out by using the nifty shape2mesh() function found in the HeightField demo which renders the CANNON body objects into visible meshes that the HeightField was tilted 90 degrees on the X axis! I had to use this line of code to rotate it back to a desired horizontal plane.  I think it has something to do with CANNON not using the same hand coordinate system as THREEJS or something alike.

Solution line of code:
heightfieldBody.shapeOrientations[0].setFromAxisAngle(new CANNON.Vec3(1,0,0), -Math.PI * 0.5);

What I think the issue is:
https://www.evl.uic.edu/ralph/508S98/coordinates.html

**Comment by brundonsmith** [comment]
I'm still confused by Heightfield. In the docs, `data` is a 1-dimensional array. It seemed strange to me when I read it (how did it know where to put the height values on the other two dimensions?), but now in this example it's a 2D array?

**Comment by that-ben** [comment]
Wow, it's been 3 years already! @brundonsmith Well, for my part, I use a single dimension array like the following and it works perfectly fine.  When you think about it, the only thing the HeightField component needs is a series of height values.  It's a square, so it doesn't need to know how wide/deep it is, since you take the number of elements from the array and you square root it, which gives you the square length... no need for 2 dimensions when it's a square.

```
// Create the heightfield shape
var data = [];
for(var iy = 0; iy < chunkResolutionDepth; iy++){
	data.push([]);
	for(var ix = 0; ix < chunkResolutionWidth + 1; ix++){
		data[iy].push(parseFloat(arr_terrain_heights[iy * chunkResolutionWidth + ix]));
	}
}
```

**Comment by brundonsmith** [comment]
Hmm... So it assumes it's a square when it's a one-dimensional array? That seems limiting. Or it would, if 2D arrays didn't work, but through some trial and error I got a 2D array working last night...

**Comment by that-ben** [comment]
> So it assumes it's a square when it's a one-dimensional array? That seems limiting.

Why would you expect it to behave differently? If I gave you only a list of values, how would you know how wide and how deep the surface is supposed to be? IMO, a single dimension array makes perfect sense to be a square if the square root of the number of items in the array is an integer.  Seems perfectly logical to me.

**Comment by brundonsmith** [comment]
Logical as a fallback, I suppose, but I don't see why someone would ever opt for a 1D array to represent 2D data. Also, it would be easy to add a pair of extra parameters for the data width and data height so it wasn't limited to a square (this is how three.js's heightmap object works).

All that said, the real issue is just that none of this is documented whatsoever; it took me multiple hours of trial and error to a) confirm that 2D data could be used, and b) figure out what orientation things ended up in and how to orient them the way I wanted.

**Comment by that-ben** [comment]
This conversation is getting way off topic, but to help you learn/understand how 3D programming works a little bit, in a nutshell, any 3D vectorial data is almost always sent to the GPU as 1-D array.  The GPU then reads the 3 different strides in the 1-D array to make X, Y, Z coordinates, for instance.  https://en.wikipedia.org/wiki/Stride_of_an_array

Any number of "channels" or components you may think of can be stored in a 1-D array, given the process that picks it up afterwards knows how to read the strides.

> b) figure out what orientation things ended up in and how to orient them the way I wanted.

See my 3 years old post right here in this exact same thread you're posting in for the answer.  https://github.com/schteppe/cannon.js/issues/221#issuecomment-128879099

**Comment by brundonsmith** [comment]
I concede that this is getting off-topic and that it would be more helpful for me to submit a pull request to the docs rather than complaining here.
