### ISSUE TITLE
Plane is still penetrated with many iterations, low tolerance and low time-step

### ISSUE THREAD

**Issue by josephrocca** [schteppe/cannon.js#237]
Hey Scteppe,

I was playing around with some basic stuff and noticed that my spheres were penetrating the ground plane when dropped from about 100m. The cubes are 3*3*3 and the spheres have a radius of 3. The spheres penetrate but the boxes don't (much).

I guessed that it was because they were heavier than the boxes, and so I went about trying to tune `solver.iterations`, `solver.tolerance` and `world.dt` to fix it - but I couldn't.

`dt` appears to have a maximum value of around `1/500` (if I set it higher, it somehow defaults to `1/60`) and even at this value I couldn't stop the spheres penetrating...

![cannon plane pen](https://cloud.githubusercontent.com/assets/1167575/10241480/e7987f62-691b-11e5-910b-db1c89ba6bc5.png)

My new guess is that the spheres are just too large/heavy for cannon - which is completely understandable, since their density is 1000kg per cubic metre. Just wanted to check with you that this is the case.

Cheers

**Comment by schteppe** [comment]
Maybe. I've tuned cannon.js to work well with values around 1. Sizes of about 1 meter. Masses about 1 kg. Follow that and see what happens. 

You're setting world.dt? You should pass the time step to world.step() instead !

Does it get better if you use zero friction? Just curious. In that case it might be worth reducing the friction and maybe also sorting the equations so that the friction is solved after the contacts... Not sure if that's possible to do right now though.

**Comment by josephrocca** [comment]
Woops, okay turns out I was setting world.dt *and* giving it to the step function... fixed that.

After adjusting the masses to around 1kg, everything behaves perfectly! I didn't see too much change when I set the friction to zero.

So I guess I'll change by default object density to 1kg per cubic metre? Seems a little strange - but if it makes my bodies behave, I'm happy! Thanks for all your help :)
