### ISSUE TITLE
Does limiting velocity require timescaling?

### ISSUE THREAD

**Issue by DelvarWorld** [schteppe/cannon.js#271]
I'm trying to limit the velocity of my player to a certain velocity. However what I can't wrap my head around is whether or not this limit should be timescaled every frame. As in

```js
player.velocity.x = Math.min( maxVelocity, player.velocity.x )
```

Should a timescale be used anywhere in the above equation, or does cannonjs handle scaling velocities?

I looked at http://schteppe.github.io/cannon.js/examples/js/PointerLockControls.js and there is a timescale:

```js
if ( moveForward ){
    inputVelocity.z = -velocityFactor * delta;
}
```

However I can't figure out why the player doesn't accelerate infinitely, because the velocity should keep increasing every frame:

````js
// Add to the object
velocity.x += inputVelocity.x;
```

**Comment by schteppe** [comment]
I think it will be fine if you do the clamping inside the ```postStep``` event. Why would you scale this limit?

The frame ```delta``` value does indeed scale the *impulse* that is added to the body each frame. If you have a frame rate of 30Hz, it will add half as much as if you have 60Hz.

The body would probably accelerate infinitely if there was no friction and no damping. But since this line is added, it will counter add a counter-impulse on each tick:

```js
sphereBody.linearDamping = 0.9;
```

Now when I look at my old code, I see that it should be re-written. Inputs could for sure be handled in a better way. The impulses should probably be added in ```postStep``` instead of in the render loop. But anyway, I hope I shed some light on this.

**Comment by DelvarWorld** [comment]
Thanks!
