### ISSUE TITLE
Outdated builds

### ISSUE THREAD

**Issue by swift502** [schteppe/cannon.js#387]
March 28th 2015 was the last build update.
Later that year @schteppe fixed body interpolation, which [I'm in dire need of](https://github.com/schteppe/cannon.js/pull/386).

Why was there no build update for 3 years? Any chance to get it?
Should I just do it myself?

What version of Cannon is [canvas_interpolation.html](https://github.com/schteppe/cannon.js/blob/master/examples/canvas_interpolation.html) supposed to run on? Because it doesn't work with 0.6.2.

I'm sorry if I'm missing something here. I'm really enjoying Cannon so far.

**Comment by swift502** [comment]
Just built it myself, interpolation works, no errors. I'm really confused, why is the official build so old?

**Comment by schteppe** [comment]
There are a number of new stuff in the master branch that I wanted to test before a new release. Didn’t want to push out broken code to a lot of people. And then I got other work to do.
I only update the build/ directory when releasing... so that’s why things are out of sync. Adding builds to every commit doesn’t make sense to me. Build locally and everything should be working.

**Comment by swift502** [comment]
Ok, I see. It's really good to hear things are still being done. 3 years just seems like a long time. And I was confused because the interpolation issue specifically seemed to have been fixed in 2015, and the canvas example made me think something must be wrong.

I wish you good luck. Cannon is incredible.
