### ISSUE TITLE
Why is halfExtents？

### ISSUE THREAD

**Issue by xuhuanstudio** [schteppe/cannon.js#388]
Hello, why does Box use the halfExtents parameter is not the actual size, so this is not complicated?

**Comment by swift502** [comment]
I was wondering the same. It's a bit confusing when working in conjunction with three.js for example.

But it's not that terrible, you can obviously easily get around it by halving your size, that is:
`new THREE.BoxGeometry(size) = new CANNON.Box(size/2)`

I certainly wouldn't expect it to change anytime soon due to compatibility reasons. It is what it is. But I can't speak for Schteppe.

**Comment by xuhuanstudio** [comment]
@swift502 
I have now consulted a colleague, and the answer is that "halfExtents" refers to a vector, that the center reaches a vector to a point on the right, so that it is easy to calculate the rotation through the matrix, but I still think why not as a vector to the upper right corner of the lower left corner, not the center point, even if it is to the center. vector, we can also use the "size" parameter.

**Comment by swift502** [comment]
I don't understand what you're trying to achieve. 
You can't change it because it would brake people's code. And I don't find it confusing, halfExtents is simply the size divided by two. It's not **that** difficult to understand and work around.

Also, I have no idea what rotations and matrices have to do with this.
Sorry. Maybe Schteppe will be able to help you.
