### ISSUE TITLE
Creating a wind tunnel simulator?

### ISSUE THREAD

**Issue by robertleeplummerjr** [schteppe/cannon.js#400]
Curious if this would be easily possible.

**Comment by ubernaut** [comment]
I think it would. You'd use an SPH system https://github.com/schteppe/cannon.js/blob/master/demos/sph.html
http://schteppe.github.io/cannon.js/demos/sph.html

Then have them moving across the wind tunnel volume. Spawning/despawning them at either end. 

Then you'd insert some solid object for them to bounce off of. 

This is me guessing by the way.

**Comment by robertleeplummerjr** [comment]
So you'd change the gravity to be horizontal as well?  How would the particles act against the wing?  Would they sumulate the vacuum that causes lift?

**Comment by ubernaut** [comment]
prefacing this with: I AM NOT A PHYSICIST

What are you trying to achieve?  do you want to integrate a wind tunnel into an existing application that's using cannon.js?  (Like a flight sim for example)

Are you trying to create a physically accurate simulation you can use to test aerodynamic characteristics of various objects for the real world?

I asked my friend  Ryan with a physics degree about an old particle based wind tunnel he wrote he said:

>"For large scale simulations you assume the fluid is a continuum not a particle So they lend to the navier stokes equations."

So if you want to be accurate, you'll be better off using an actual fluid dynamics simulation. In which case you should probably ditch cannon.js and use a dedicated fluid dynamics library.  (Or if you're indomitably brave with the time and have the chops to learn academic level fluid dynamics build one for GPU.JS :D)  

Ryan had a particle based wind tunnel simulation in 2d running in java around 10 years ago.  It did demonstrate the airflow for lift but it didn't calculate the force generated by it.   After talking with him, he says it wasn't an SPH sim. Just a super simple particle collision simulation.  I do think an SPH sim would work, and I suspect it would do a better job of showing the pressure difference between the top and bottom of the wing.   At the same time it wouldn't be accurate or large scale enough for you to simulate macroscopic aerodynamic phenomena and derive realistic values for lift.  A proper fluid sim would do a better job.  

If you still want to go ahead using cannon.js to build a particle based wind tunnel read on:

I would remove the gravity entirely and spawn the particles with an initial velocity. Otherwise, they would be accelerating from one end of the tunnel to the other.  You will want to warp the particles from one end of the tunnel to the other and reset their velocity when doing it.  This will be computationally less expensive than spawning/despawning new particles. 

If you added a vertical gravity component to everything in the system you would demonstrate a dramatic difference in pressure between the top of the wing and the bottom of the wing even without motion which is obviously undesirable.

Play with the constants until you get a nice laminar flow https://en.wikipedia.org/wiki/Laminar_flow   do this before putting a wing in the tunnel.   After toying with the SPH demo a bit this will take some finagling to keep particles from getting stuck in the floor and other little bugs. 

In order for you to get the particle density required to demonstrate lift you will probably have to restrict the particles into a 2d plane. 

Once  everything is tuned up and flowing smoothly add the wing. 

I hope this helps!

**Comment by ubernaut** [comment]
I messed around and set up some initial conditions that seem to work OK for what I was talking about:

https://github.com/ubernaut/cannon.js/blob/master/demos/sph.html 

I have not set up any initial velocities or made this so it will warp the particles from one side to the other yet.

**Comment by ubernaut** [comment]
https://i.imgur.com/PquoRDG.png 

This is actually working pretty well now. That was fun!

**Comment by robertleeplummerjr** [comment]
Ty for putting this together!  My son (who is 7) was the one who proposed this as a feature, I look forward to playing with it with him
