### ISSUE TITLE
Rolling dice quaternion question

### ISSUE THREAD

**Issue by milanzigmond** [schteppe/cannon.js#401]
Hi guys, I'm making a 3d dice game and came to one issue I can't wrap my head around so I'm turning to you for help. 

In the scene/world (using threejs with cannon) I have a plane and one die, which I'm throwing on the plane (screenshots here pre-roll http://prntscr.com/l9rat5, result http://prntscr.com/l9rdeb). All works fine, until I want to throw some specific value on a die like 1 for example. 

Since I'm using loaded models instead of texture images for faces of the cube, I cannot handle this just by changing faces of the cube in threejs (since model has 100s of them). Therefore I was hoping I can achieve this by somehow changing the initial quaternion of the body (kind of pre-rotate it) so the die falls on a specific side. The die mesh is just following the body position and quaternion.

I have these questions:

1. Is this even possible to do? Maybe when I change quaternion pre throw it will result always in different final quaternion, which I can not determine? If it is not possible to do with quaternions, any tips?

2. If it is possible, how do I figure out by which quaternion do I need to multiply my initial one to get desired result value 1? I have available the final quaternion and I know which values are on each face from emulated throw so I was trying to play with quaternion inverse but no luck. 

If I just rotate the initial body so that face 1 rotates to the result face (eg. 6) it works in some cases (i throw 1 when emulated result was 6), but when the throw gets more complicated (more rotations) it is not working of course since I'm not counting on all possible rotations.

If it is not clear what I mean let me know pls.

Thanks a lot
m

**Comment by schteppe** [comment]
Hello,
It sounds like it should be possible to do.

First of all, make sure that you use fixed step simulation. You do this by passing 3 arguments to world.step() instead of one. This will make sure that your simulation will behave the same every time, regardless of frame rate.

Also make sure that your initial position, velocity and force of the die is the same every throw.

If you construct the quaternion using the built in cannon functions, like `.setFromAxisAngle()`, all should be good... Use .setFromAxisAngle() with even 90-degree angles around different axis. Why bother using quaternion inverse?

If you want an alternative way of rotating the die, put the mesh below an empty parent mesh in your scene. During simulation, copy the cannon.js output to the parent mesh. Then rotate the child die mesh to get the desired initial (and end) rotation. Does this make sense?

**Comment by milanzigmond** [comment]
thank you for the answers schteppe
- yes, i'm using all 3 argumetns
- positon, velocity, force are the same
- I was trying to do it using .setFromAxisAngle() but it didn't work all the times, I guess because you can rotate 1 to 6 using x or y axis, which will give you different dice values on other sides of a die, so I need to know also the axis and also angle of rotation, which I'm not sure how to find out from final quaternion
- right now I'm trying to use a technique of rotating the threejs geometry, while the quaternion is untouched, ... having the best results but still not 100% accuracy, I guess also because of the problem of multiple possible ways how to rotate one face to another

**Comment by milanzigmond** [comment]
For the note, I solved it by rotating just the geometry (not mesh) in threejs and not touching the quaternion of the body at all. Thanks.
